spec:
  replicas: 1
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.002"
              memory: 400Mi
            limits:
              cpu: "0.5"
              memory: 600Mi